### ISSUE TITLE
Support passing custom ethereum network spec via CLI

### ISSUE THREAD

**Issue by mksh** [ChorusOne/eth-staking-smith#22]
Context: Right now custom network spec can be passed via library interface, but not via command line interface. This is required when generating keys for private testnets, e.g. for Helder devnet

**Comment by jenpaff** [comment]
> Right now custom network spec can be passed via library interface, but not via command line interface.

what's the use case for using the CLI right now? Actually was thinking to not recommend the cli tool before picking up #25 given the feedback we received a while back

**Comment by mksh** [comment]
@jenpaff It's for our Helder devnet participation

**Comment by mksh** [comment]
Individual staker guide was merged, now available on master: https://github.com/ChorusOne/eth-staking-smith?tab=readme-ov-file#exporting-cli-standard-output-into-common-keystores-folder-format

**Comment by jenpaff** [comment]
> @jenpaff It's for our Helder devnet participation

ok was missing this context- will add to PR & github issue
